CREATE OR REPLACE PACKAGE BODY mfs_pkg AS
  FUNCTION authenticate_user(p_email IN VARCHAR2, p_password_hash IN VARCHAR2, p_role_code IN VARCHAR2) RETURN NUMBER IS v_user_id NUMBER; BEGIN SELECT u.user_id INTO v_user_id FROM mfs_users u JOIN mfs_roles r ON r.role_id = u.role_id WHERE u.email = LOWER(TRIM(p_email)) AND u.password_hash = p_password_hash AND r.role_code = UPPER(TRIM(p_role_code)) AND u.status = 'ACTIVE'; RETURN v_user_id; EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL; END authenticate_user;
  FUNCTION user_role(p_user_id IN NUMBER) RETURN VARCHAR2 IS v_role_code VARCHAR2(20); BEGIN SELECT r.role_code INTO v_role_code FROM mfs_users u JOIN mfs_roles r ON r.role_id = u.role_id WHERE u.user_id = p_user_id; RETURN v_role_code; END user_role;
  FUNCTION product_avg_rating(p_product_id IN NUMBER) RETURN NUMBER IS v_rating NUMBER; BEGIN SELECT ROUND(AVG(rating),2) INTO v_rating FROM mfs_feedbacks WHERE product_id = p_product_id AND status = 'VISIBLE'; RETURN NVL(v_rating,0); END product_avg_rating;
  FUNCTION product_feedback_count(p_product_id IN NUMBER) RETURN NUMBER IS v_count NUMBER; BEGIN SELECT COUNT(*) INTO v_count FROM mfs_feedbacks WHERE product_id = p_product_id AND status = 'VISIBLE'; RETURN v_count; END product_feedback_count;
  FUNCTION seller_pending_replies(p_seller_id IN NUMBER) RETURN NUMBER IS v_count NUMBER; BEGIN SELECT COUNT(*) INTO v_count FROM mfs_feedbacks f JOIN mfs_products p ON p.product_id = f.product_id WHERE p.seller_id = p_seller_id AND f.status = 'VISIBLE' AND f.seller_reply IS NULL; RETURN v_count; END seller_pending_replies;
  FUNCTION unread_notifications(p_user_id IN NUMBER) RETURN NUMBER IS v_count NUMBER; BEGIN SELECT COUNT(*) INTO v_count FROM mfs_notifications WHERE user_id = p_user_id AND is_read = 'N'; RETURN v_count; END unread_notifications;
  FUNCTION low_stock_products(p_threshold IN NUMBER DEFAULT 5) RETURN t_id_list IS v_products t_id_list; v_index PLS_INTEGER := 0; BEGIN FOR product_row IN (SELECT product_id FROM mfs_products WHERE stock_qty <= p_threshold AND status = 'ACTIVE' ORDER BY stock_qty ASC) LOOP v_index := v_index + 1; v_products(v_index) := product_row.product_id; END LOOP; RETURN v_products; END low_stock_products;
  PROCEDURE create_user(p_role_code IN VARCHAR2, p_full_name IN VARCHAR2, p_email IN VARCHAR2, p_password_hash IN VARCHAR2, p_user_id OUT NUMBER) IS v_role_id NUMBER; BEGIN SELECT role_id INTO v_role_id FROM mfs_roles WHERE role_code = UPPER(TRIM(p_role_code)); INSERT INTO mfs_users(user_id, role_id, full_name, email, password_hash) VALUES(seq_mfs_users.NEXTVAL, v_role_id, TRIM(p_full_name), LOWER(TRIM(p_email)), p_password_hash) RETURNING user_id INTO p_user_id; END create_user;
  PROCEDURE add_product(p_seller_id IN NUMBER, p_category_id IN NUMBER, p_product_name IN VARCHAR2, p_description IN VARCHAR2, p_price IN NUMBER, p_stock_qty IN NUMBER, p_product_id OUT NUMBER) IS BEGIN INSERT INTO mfs_products(product_id, seller_id, category_id, product_name, description, price, stock_qty) VALUES(seq_mfs_products.NEXTVAL, p_seller_id, p_category_id, TRIM(p_product_name), p_description, p_price, p_stock_qty) RETURNING product_id INTO p_product_id; END add_product;
  PROCEDURE submit_feedback(p_product_id IN NUMBER, p_buyer_id IN NUMBER, p_rating IN NUMBER, p_message IN VARCHAR2, p_feedback_id OUT NUMBER) IS BEGIN INSERT INTO mfs_feedbacks(feedback_id, product_id, buyer_id, rating, message) VALUES(seq_mfs_feedbacks.NEXTVAL, p_product_id, p_buyer_id, p_rating, TRIM(p_message)) RETURNING feedback_id INTO p_feedback_id; END submit_feedback;
  PROCEDURE reply_feedback(p_seller_id IN NUMBER, p_feedback_id IN NUMBER, p_reply IN VARCHAR2) IS BEGIN UPDATE mfs_feedbacks SET seller_reply = TRIM(p_reply), replied_at = SYSDATE WHERE feedback_id = p_feedback_id; END reply_feedback;
  PROCEDURE delete_feedback(p_admin_id IN NUMBER, p_feedback_id IN NUMBER, p_reason IN VARCHAR2) IS BEGIN UPDATE mfs_feedbacks SET status = 'DELETED' WHERE feedback_id = p_feedback_id; INSERT INTO mfs_audit_log(audit_id, table_name, record_id, action_name, new_value) VALUES(seq_mfs_audit.NEXTVAL, 'MFS_FEEDBACKS', p_feedback_id, 'ADMIN_DELETE', p_reason); END delete_feedback;
  PROCEDURE update_product_stock(p_seller_id IN NUMBER, p_product_id IN NUMBER, p_new_stock IN NUMBER) IS BEGIN UPDATE mfs_products SET stock_qty = p_new_stock, updated_at = SYSDATE WHERE product_id = p_product_id; END update_product_stock;
  PROCEDURE mark_notification_read(p_user_id IN NUMBER, p_notification_id IN NUMBER) IS BEGIN UPDATE mfs_notifications SET is_read = 'Y' WHERE notification_id = p_notification_id AND user_id = p_user_id; END mark_notification_read;
  PROCEDURE dashboard_stats(p_user_id IN NUMBER, p_stats OUT t_dashboard_stats) IS BEGIN SELECT COUNT(*) INTO p_stats.total_products FROM mfs_products WHERE status = 'ACTIVE'; SELECT COUNT(*), ROUND(NVL(AVG(rating),0),2) INTO p_stats.total_feedbacks, p_stats.average_rating FROM mfs_feedbacks WHERE status = 'VISIBLE'; SELECT COUNT(*) INTO p_stats.pending_replies FROM mfs_feedbacks WHERE status = 'VISIBLE' AND seller_reply IS NULL; SELECT COUNT(*) INTO p_stats.unread_notifications FROM mfs_notifications WHERE user_id = p_user_id AND is_read = 'N'; END dashboard_stats;
END mfs_pkg;
/
